### PR TITLE
rebased with x11-rdp1.2

### PR DESCRIPTION
**Pull request by sparklyballs**
fixed up symlink to dri , added python-xdg and fixed up firstrun.sh with setuser in place of su.

the calibre wizard comes up, haven't tested beyond that, so at your own peril, lol.

### CODE REVIEW

**Comment by aptalca** [comment]
Man, you got me excited.

I put these changes into my dev docker, fired it up and got the same result. Then I tried a fresh install, so I selected a new local folder and reinstalled. Like you said, the wizard comes up, but once you go through the wizard, and it's time to launch the actual app, you get the segmentation fault.

Not sure why the xrdp branch causes it, but the vnc doesn't.

**Comment by sparklyballs** [comment]
i just took another look. 

your firstrun.sh seems to start the app, and then you seem to start it again in the startapp file.

**Comment by aptalca** [comment]
firstrun starts the calibre-server, that's the built-in watered down webui, only good for sharing the library, not managing.
startapp starts calibre, the desktop gui

They run simultaneously as the calibre-server is read-only

**Comment by sparklyballs** [comment]
is there a possibility of a dependency issue, something in the xvnc image that isn't in or different version in x11rdp image ? 
have you ran an ldd on calibre ?

**Pull request closed without merging**
